<a href="https://colab.research.google.com/github/Neeraton/Digital-communication/blob/main/neeraj_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

m=np.array([0,0,1,1])
g=np.array([1,1,0,1])
print(m)
print(g)

mx=np.poly1d(m)
gx=np.poly1d(g)
print(mx)
print(gx)

[0 0 1 1]
[1 1 0 1]
 
1 x + 1
   3     2
1 x + 1 x + 1


In [ ]:
parity=np.zeros(len(g))
parity[0]=1
print(parity)

parity_x=np.poly1d(parity)
print(parity_x)

[1. 0. 0. 0.]
   3
1 x


In [ ]:
shifted_mx=np.polymul(parity_x,mx)
print(shifted_mx)


   4     3
1 x + 1 x


In [ ]:
q,r=np.polydiv(shifted_mx,gx)
r=np.absolute(r)%2
print(r)

[1. 0.]


In [ ]:
rem=np.insert(r,0,0)
print(rem)

[0. 1. 0.]


In [ ]:
code=np.append(m,rem)
print(code)

[0. 0. 1. 1. 0. 1. 0.]
