<a href="https://colab.research.google.com/github/Neeraton/Digital-communication/blob/main/neeraj_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

M=np.array([1,0,1,1,0,1])
d=np.array([1,0,1,1])
L=len(d)
print("M=",M)
print("d=",d)
print(L)

M= [1 0 1 1 0 1]
d= [1 0 1 1]
4


In [ ]:
t=np.zeros(L)
t[0]=1
print(t)

[1. 0. 0. 0.]


In [ ]:
Mx=np.poly1d(M)
dx=np.poly1d(d)
tx=np.poly1d(t)
print("Mx=\n",Mx)
print("dx=\n",dx)
print("tx=\n",tx)

Mx=
    5     3     2
1 x + 1 x + 1 x + 1
dx=
    3
1 x + 1 x + 1
tx=
    3
1 x


In [ ]:
aMx=np.polymul(Mx,tx)
print(aMx)

   8     6     5     3
1 x + 1 x + 1 x + 1 x


In [ ]:
qx,rx=np.polydiv(aMx,dx)
rx=np.absolute(rx)%2
print(rx)

[1. 1.]


In [ ]:
Cx=aMx+rx
print(Cx)

   8     6     5     3
1 x + 1 x + 1 x + 1 x + 1 x + 1


In [ ]:
C=Cx.c
print(C)

[1. 0. 1. 1. 0. 1. 0. 1. 1.]


In [ ]:
#decoding
R=C
loc=4
R[loc]=int(not (R[loc]))
print(R)

[1. 0. 1. 1. 1. 1. 0. 1. 1.]


In [ ]:
Rx=np.poly1d(R)
print(Rx)

   8     6     5     4     3
1 x + 1 x + 1 x + 1 x + 1 x + 1 x + 1


In [ ]:
Qx,Rx=np.polydiv(Rx,dx)
Re=Rx.c%2
print(Re)

[1. 1. 0.]


In [ ]:
f=0
for i in Re:
  if i!=0:
    print("Error Detected")
    f=1
    break
  if f==0:
    print("Error not detected")

Error Detected
