<a href="https://colab.research.google.com/github/Neeraton/Digital-communication/blob/main/neeraj_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

g1=np.array([0,1,1])
g2=np.array([1,0,1])
m=np.array([1,0,1,0,1])
print("g1=",g1)
print("g2=",g2)
print("m=",m)

g1= [0 1 1]
g2= [1 0 1]
m= [1 0 1 0 1]


In [ ]:
#for time doamin
V1=np.convolve(m,g1)
V1=V1%2
V2=np.convolve(m,g2)
V2=V2%2

print(V1)
print(V2)

[0 1 1 1 1 1 1]
[1 0 0 0 0 0 1]


In [ ]:
#combining both o/p
code=np.zeros((V1.shape[0],2))
for i in range(V1.shape[0]):
  code[i,:]=[V1[i],V2[i]]
code=code.flatten()
print(code)

[0. 1. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 1.]


In [ ]:
#for transfer domain
g1_x=np.poly1d(g1)
g2_x=np.poly1d(g2)
m_x=np.poly1d(m)
print("g1_x=\n",g1_x)
print("g2_x=\n",g2_x)
print("m_x=\n",m_x)

g1_x=
  
1 x + 1
g2_x=
    2
1 x + 1
m_x=
    4     2
1 x + 1 x + 1


In [ ]:

V1=np.polymul(m_x,g1_x)
V1=V1.c%2
V2=np.polymul(m_x,g2_x)
V2=V2.c%2

print(V1)
print(V2)

[1 1 1 1 1 1]
[1 0 0 0 0 0 1]


In [ ]:
#combining both o/p
code=np.zeros((V1.shape[0],2))
for i in range(V1.shape[0]):
  code[i,:]=[V1[i],V2[i]]
code=code.flatten()
print(code)

[1. 1. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
