<a href="https://colab.research.google.com/github/Neeraton/Digital-communication/blob/main/neeraj_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

p_xy=np.array([[1/8,1/16,1/32,1/32],[1/16,1/8,1/32,1/32],[1/16,1/16,1/16,1/16],[1/4,0,0,0]])
print(p_xy)

[[0.125   0.0625  0.03125 0.03125]
 [0.0625  0.125   0.03125 0.03125]
 [0.0625  0.0625  0.0625  0.0625 ]
 [0.25    0.      0.      0.     ]]


In [ ]:
prob=p_xy.flatten()
print(prob)


[0.125   0.0625  0.03125 0.03125 0.0625  0.125   0.03125 0.03125 0.0625
 0.0625  0.0625  0.0625  0.25    0.      0.      0.     ]


In [ ]:
h_xy=-(np.sum([p*np.log2(p) for p in prob if p>0]))
print(h_xy)

3.375


In [ ]:
p_x=np.sum(p_xy,axis=1)
print(p_x)

[0.25 0.25 0.25 0.25]


In [ ]:
p_y=np.sum(p_xy,axis=0)
print(p_y)

[0.5   0.25  0.125 0.125]


In [ ]:
h_x=-(np.sum([p*np.log2(p) for p in p_x if p>0]))
print(h_x)

2.0


In [ ]:
h_y=-(np.sum([p*np.log2(p) for p in p_y if p>0]))
print(h_y)

1.75


In [ ]:
p_xgiveny=p_xy/p_y
print(p_xgiveny)

[[0.25  0.25  0.25  0.25 ]
 [0.125 0.5   0.25  0.25 ]
 [0.125 0.25  0.5   0.5  ]
 [0.5   0.    0.    0.   ]]


In [ ]:
p_ygivenx=p_xy/p_x
print(p_ygivenx)

[[0.5   0.25  0.125 0.125]
 [0.25  0.5   0.125 0.125]
 [0.25  0.25  0.25  0.25 ]
 [1.    0.    0.    0.   ]]


In [ ]:
mask=p_xgiveny>0
h_xgiveny=-(np.sum([p_xy[mask]*np.log2(p_xgiveny[mask])]))
print(h_xgiveny)

1.625


In [ ]:
mask=p_ygivenx>0
h_ygivenx=-(np.sum([p_xy[mask]*np.log2(p_ygivenx[mask])]))
print(h_ygivenx)

1.375


In [ ]:
I_xy=h_x+h_y-h_xy
print(I_xy)

0.375
