<a href="https://colab.research.google.com/github/Neeraton/Digital-communication/blob/main/neeraj_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

n=7
k=4
p=np.array([[0,1,1],[1,1,1],[1,1,0],[1,0,1]])
print(p)

[[0 1 1]
 [1 1 1]
 [1 1 0]
 [1 0 1]]


In [ ]:
I=np.eye(k)
print(I)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
G=np.hstack((I,p))
print(G)

[[1. 0. 0. 0. 0. 1. 1.]
 [0. 1. 0. 0. 1. 1. 1.]
 [0. 0. 1. 0. 1. 1. 0.]
 [0. 0. 0. 1. 1. 0. 1.]]


In [ ]:
m=np.arange(2**k)
print(m)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [ ]:
D=np.zeros((2**k,k))
for i in m:
  z='{0:04b}'.format(i)
  zs=[int(i) for i in z]
  D[i,:]=zs
print(D)

[[0. 0. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 1. 0.]
 [0. 0. 1. 1.]
 [0. 1. 0. 0.]
 [0. 1. 0. 1.]
 [0. 1. 1. 0.]
 [0. 1. 1. 1.]
 [1. 0. 0. 0.]
 [1. 0. 0. 1.]
 [1. 0. 1. 0.]
 [1. 0. 1. 1.]
 [1. 1. 0. 0.]
 [1. 1. 0. 1.]
 [1. 1. 1. 0.]
 [1. 1. 1. 1.]]


In [ ]:
c=np.dot(D,G)
print(c)
c=c%2
c=c.astype(int)
print(c)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 1. 0. 1.]
 [0. 0. 1. 0. 1. 1. 0.]
 [0. 0. 1. 1. 2. 1. 1.]
 [0. 1. 0. 0. 1. 1. 1.]
 [0. 1. 0. 1. 2. 1. 2.]
 [0. 1. 1. 0. 2. 2. 1.]
 [0. 1. 1. 1. 3. 2. 2.]
 [1. 0. 0. 0. 0. 1. 1.]
 [1. 0. 0. 1. 1. 1. 2.]
 [1. 0. 1. 0. 1. 2. 1.]
 [1. 0. 1. 1. 2. 2. 2.]
 [1. 1. 0. 0. 1. 2. 2.]
 [1. 1. 0. 1. 2. 2. 3.]
 [1. 1. 1. 0. 2. 3. 2.]
 [1. 1. 1. 1. 3. 3. 3.]]
[[0 0 0 0 0 0 0]
 [0 0 0 1 1 0 1]
 [0 0 1 0 1 1 0]
 [0 0 1 1 0 1 1]
 [0 1 0 0 1 1 1]
 [0 1 0 1 0 1 0]
 [0 1 1 0 0 0 1]
 [0 1 1 1 1 0 0]
 [1 0 0 0 0 1 1]
 [1 0 0 1 1 1 0]
 [1 0 1 0 1 0 1]
 [1 0 1 1 0 0 0]
 [1 1 0 0 1 0 0]
 [1 1 0 1 0 0 1]
 [1 1 1 0 0 1 0]
 [1 1 1 1 1 1 1]]


In [ ]:
idx=4
loc=2
R=c[idx,:]
print("original R",R)
R[loc]=int(not R[loc])
print("new R",R)

original R [0 1 0 0 1 1 1]
new R [0 1 1 0 1 1 1]


In [ ]:
I=np.eye(n-k)
print(I)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
H=np.hstack((p.T,I))
print(H)

[[0. 1. 1. 1. 1. 0. 0.]
 [1. 1. 1. 0. 0. 1. 0.]
 [1. 1. 0. 1. 0. 0. 1.]]


In [ ]:
x=H.T
print(x)

[[0. 1. 1.]
 [1. 1. 1.]
 [1. 1. 0.]
 [1. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
s=np.dot(R,x)
s=s%2
print(s)

[1. 1. 0.]


In [ ]:
for i in range(x.shape[1]):
  if np.array_equal(s,x[i,:]):
    R[i]=int(not R[i])
    print("Error present at ",i)
    break
print("Correctect codeword =",R)

Error present at  2
Correctect codeword = [0 1 0 0 1 1 1]
